### ISSUE TITLE
no cameras connected issue in installing libroyale drivers in tegra board though the camera is connected

### ISSUE THREAD

**Issue by chetansarmak** [code-iai/pico_flexx_driver#16]
I am using Pico Flexx camera ,connected to my system with ubuntu 14.04 .It gives me following error
core service [/rosout] found
process[pico_flexx_static_tf-1]: started with pid [8510]
process[pico_flexx-2]: started with pid [8511]
process[pico_flexx_driver-3]: started with pid [8512]
[ INFO] [1519887740.596905650]: Loading nodelet /pico_flexx_driver of type pico_flexx_driver/pico_flexx_nodelet to manager pico_flexx with the following remappings:
[ INFO] [1519887740.602943459]: waitForService: Service [/pico_flexx/load_nodelet] has not been advertised, waiting...
[ INFO] [1519887740.699118144]: Initializing nodelet with 2 worker threads.
[ INFO] [1519887740.711950258]: waitForService: Service [/pico_flexx/load_nodelet] is now available.
[ INFO] [1519887740.845395789]: [PicoFlexx::initialize] parameter:
base_name: pico_flexx
sensor: default
use_case: 0
automatic_exposure: true
automatic_exposure_stream2: true
exposure_time: 1000
exposure_time_stream2: 1000
max_noise: 0.07 meters
range_factor: 2
queue_size: 5
base_name_tf: pico_flexx
[ INFO] [1519887740.845530122]: [PicoFlexx::initialize] libroyale version: 3.12.0.44
[ERROR] [1519887740.854464419]: [PicoFlexx::selectCamera] no cameras connected!

But the camera is connected and shows when i give dmesg command also

where am i going wrong ? and I am using Tegra board.
Thanks in advance

**Comment by mintar** [comment]
Hmmm. Did you install the udev rules? Just a shot in the dark, I haven't tested the driver on ARM.

**Comment by chetansarmak** [comment]
Yes ,I have installed udev rules and libroyale compiled using c++11 and tegra has ROS with  c++98 will that be a problem ??
I have followed the same steps given in the Readme file....it's of armv7l architecture ,should I change something in the cpp codes to make cameramanager to list cameras ??

**Comment by mintar** [comment]
No, c++11 vs. c++98 won't be a problem. If that were a problem, the compiler would have thrown an error.

I just remembered that I've tried before to run the camera on an ARM board and couldn't get it to work, see #15. So unfortunately I can't help you. :(

**Comment by chetansarmak** [comment]
Thank you mintar for the help, I will update you if I get any solution by chance :)

**Comment by chetansarmak** [comment]
Hi mintar ,I got this problem solved by changing the permissions for the device file name camboard-XXX  under /dev ...If the file is not created then disconnect the camera and follow the steps of installation and once file  is created  then do that above fix.

**Comment by mintar** [comment]
Thanks for letting me know!

**Comment by TheRobotStudio** [comment]
I have the same problem on the NVIDIA Jetson TX2, using Ubuntu 16.04 with the Pico Flexx. The udev rule is in place, the symlink file is created after I plug the device:
`lrwxrwxrwx  1 root   root          15 May  8 15:58 camboard_pico_flexx-2-1.3.4 -> bus/usb/002/007`

But when I launch the roslaunch command it says that no camera is connected:
```
$ roslaunch pico_flexx_driver pico_flexx_driver.launch publish_tf:=true
... logging to /home/nvidia/.ros/log/0c95084c-52c8-11e8-982d-00044b8c3cdc/roslaunch-bibot-TX2-4461.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://bibot-TX2:33328/

SUMMARY
========

PARAMETERS
 * /pico_flexx_driver/automatic_exposure: True
 * /pico_flexx_driver/base_name: pico_flexx
 * /pico_flexx_driver/base_name_tf: pico_flexx
 * /pico_flexx_driver/exposure_time: 1000
 * /pico_flexx_driver/max_noise: 0.07
 * /pico_flexx_driver/queue_size: 5
 * /pico_flexx_driver/range_factor: 2.0
 * /pico_flexx_driver/sensor: 
 * /pico_flexx_driver/use_case: 0
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    pico_flexx (nodelet/nodelet)
    pico_flexx_driver (nodelet/nodelet)
    pico_flexx_static_tf (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [4473]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0c95084c-52c8-11e8-982d-00044b8c3cdc
process[rosout-1]: started with pid [4486]
started core service [/rosout]
process[pico_flexx_static_tf-2]: started with pid [4503]
process[pico_flexx-3]: started with pid [4504]
process[pico_flexx_driver-4]: started with pid [4515]
[ INFO] [1525787980.810347765]: Loading nodelet /pico_flexx_driver of type pico_flexx_driver/pico_flexx_nodelet to manager pico_flexx with the following remappings:
[ INFO] [1525787980.817312560]: waitForService: Service [/pico_flexx/load_nodelet] has not been advertised, waiting...
[ INFO] [1525787980.859820783]: Initializing nodelet with 6 worker threads.
[ INFO] [1525787980.885964036]: waitForService: Service [/pico_flexx/load_nodelet] is now available.
[ INFO] [1525787981.193314154]: [PicoFlexx::initialize] parameter:
                 base_name: pico_flexx
                    sensor: default
                  use_case: 0
        automatic_exposure: true
automatic_exposure_stream2: true
             exposure_time: 1000
     exposure_time_stream2: 1000
                 max_noise: 0.07 meters
              range_factor: 2
                queue_size: 5
              base_name_tf: pico_flexx
[ INFO] [1525787981.193541993]: [PicoFlexx::initialize] libroyale version: 3.16.0.51
[ERROR] [1525787981.266719973]: [PicoFlexx::selectCamera] no cameras connected!
```
Anybody has the same issue or got it working on the TX2 (aarch64) ?
Thanks!
