### ISSUE TITLE
Definition of noise in noise image

### ISSUE THREAD

**Issue by simonePasi** [code-iai/pico_flexx_driver#19]
Hi,

I can't understand which is the definition of "noise" in noise image.
It is the standard deviation of the depth pixel? Or it is the confidence level of the single depth point (95%, 99%)?

Thanks,
Simone

**Comment by mintar** [comment]
Sorry for not replying earlier, I completely overlooked this issue. The noise value is the standard deviation of the depth pixel, measured in meters. I've updated the README.
