### ISSUE TITLE
differences with other devices

### ISSUE THREAD

**Issue by flobotics** [code-iai/pico_flexx_driver#2]
hi,
i saw your the maintainer of the pico_flexx_driver and the iai_kinect2 repository and i got a question about these two devices. Perhaps you got experience of more depth-devices, like the xtion pro, orbbec persee or astra, intel realsense, etc.

my main questions are:
- the depth picture of pico_flexx_driver looks very good, if i look at the table-legs or chair-legs which are small, it seemed to look better than the one of kinect2 ? the pico flexx got only 224x171 px depth, a lot less then the kinect2 , so, does it really has a better depth than kinect2 ?
- the pico_flexx seemed to be possible to setup the range, does this affect also the depth, or is it only a zoom of the rgb picture ?
- is the pico_flexx able to detect stuff which is only some mm in diameter, like pencils, or small cables ?
- if you got experience with other rgbd devices, which is the best, or do they have all their own perfections, like lower-or-bigger ranges, more depth pixels, ir, etc. 

thanks

**Comment by kohrt** [comment]
- I think the pico flexx has a better depth than the Kinect 2. You also get a noise value per pixel, so you could use it to filter out bad points. And the resolution of the depth image has nothing to do with the quality of the depth points you get.
- There is no rgb sensor on the pico flexx. And the range is directly connected to the exposure time and the frame rate. If you make the exposure time very long, you can measure up to 7m distance, but things too near to the sensor get overexposed. And if you set it low, you can see things near by much better, down to some cm distance, but things in the back don't get exposed enough to be seen. And the frame rate limits the maximum exposure time, for 5 fps the max exposure time is 2000 µs. but for 45 fps the max exposure time is only 500 µs, so you can't see that far.
- Yes, it is possible, if the distance to the object is short.
- The Kinect2 has a great resolution and range, and the quality is ok, but it has the same issues as all ToF sensors and you can't configure it a lot, like disable auto white-balance, exposure time, etc and you need stronger hardware to run it. The pico flexx is nicely configurable, comes with an easy to use SDK, is very small in size (could be directly attached to a gripper) and has a good quality, but it costs more, has a lower resolution and the same ToF problems. And xtion like sensors have their pros and cons.

**Comment by flobotics** [comment]
thanks, for this info
