### ISSUE TITLE
CMake in ROS 

### ISSUE THREAD

**Issue by deem98** [code-iai/pico_flexx_driver#28]
hello all I am working on a project and I need help in the Cmake process the project is building a simulation environment using ROS and Gazebo and menge and I must download cmake version 3.10 or higher I have tried every thing but everytime I install it there is an error occurs in the configuration , can anyone please help me with the installation and the configuration of the Cmake 
thank you

**Comment by deem98** [comment]
@mintar

**Comment by deem98** [comment]
@michaelhuang14

**Comment by mintar** [comment]
PLEASE STOP SPAMMING THIS PROJECT! YOU ARE IN THE **WRONG PLACE**! Thank you.
