### ISSUE TITLE
depth calculation

### ISSUE THREAD

**Issue by bsbc** [code-iai/pico_flexx_driver#3]
Based on line 864 in the [pico_flexx_driver.cpp](https://github.com/code-iai/pico_flexx_driver/blob/master/src/pico_flexx_driver.cpp#L864) the depth equals the z coordinate:

`
        *itCX = itI->x;
        *itCY = itI->y;
        *itCZ = itI->z;
        *itCN = itI->noise;
        *itD = itI->z;
`

I'm not sure this is correct. Shouldn't it be the vector length instead?

**Comment by kohrt** [comment]
Hi,
theoretically it could also be the length of the ray from the camera through that pixel to the object. This might be true for laser scanners, but as far as I know, depth sensors like the Kinect, xtion, Kinect2, are returning the distance from the camera plane to the object.
For example the generation of point clouds in ROS is done the inverse way:
https://github.com/ros-perception/image_pipeline/blob/indigo/depth_image_proc/src/nodelets/register.cpp#L233-L236

**Comment by bsbc** [comment]
I don't remember the Kinect(?) anymore. However, the [O3D303](http://www.ifm.com/products/us/ds/O3D303.htm) from IFM is returning the expected/true distance from the camera plane (and not just the z component of the point cloud). See [https://github.com/lovepark/libo3d3xx](https://github.com/lovepark/libo3d3xx).

If you want to keep it this way, it may be worth mentioning in the documentation.

Regardless, your [pico_flexx package/driver](https://github.com/code-iai/pico_flexx_driver) was very helpful for us. Thanks.

**Comment by kohrt** [comment]
I mentioned it in the README.
