### ISSUE TITLE
[Question] Measurement of image_noise

### ISSUE THREAD

**Issue by tkazik** [code-iai/pico_flexx_driver#33]
First of all, thx for all you work...what a nice driver!

I have a question regarding the `image_noise` topic: According your documentation, it corresponds to the following:

> This is the distorted noise image. It is a 32-Bit float image where each pixel is a noise value of the corresponding depth pixel (standard deviation, measured in meters).

Do you have an idea how that noise is derived?

- Is it derived 'temporally'? e.g. by looking at the past N measurements? (would then probably have some sort of delay...)
- Or is is something that is effectively measured?

I wasn't able to find anything in your code or the official docs. Thx a lot!

**Comment by mintar** [comment]
Sorry, I don't have any more information than you have. The driver simply forwards the noise image as it is provided by the libroyale library. Your best bet is probably contacting pmd directly!

If you find the answer, please comment back here. I'd be interested in that as well!

**Comment by tkazik** [comment]
Ok thanks for that super-quick reply...if I find more info somewhere, I will post it in this issue...closing it for now. Thx!
