### ISSUE TITLE
[FATAL]: Failed to load nodelet '/royale_camera_driver` of type `royale_in_ros/royale_nodelet` to manager `royale_camera'

### ISSUE THREAD

**Issue by kevinapriandy** [code-iai/pico_flexx_driver#35]
I have already follow exactly step-by-step provided by this tutorial. But I found it error, Does anyone could hemp me with this?
![image](https://user-images.githubusercontent.com/51031893/204084218-6331ae79-5d5a-4cf1-a837-46558f4cdefb.png)

**Comment by mintar** [comment]
Which tutorial exactly are you following? The `royale_in_ros/royale_nodelet` is from the `libroyale` SDK; the nodelet provided by this package is called `pico_flexx_driver/pico_flexx_nodelet`, and as you can see from your error message, it exists.

The proper way to run this driver is:

```bash
roslaunch pico_flexx_driver pico_flexx_driver.launch publish_tf:=true
```

Please refer to the [README](https://github.com/code-iai/pico_flexx_driver) for information on how to install and run this driver.
