### ISSUE TITLE
Difference between intensity and gray channel

### ISSUE THREAD

**Issue by pomerlef** [code-iai/pico_flexx_driver#4]
Reading the documentation of libroyale, it seems that the driver outputs per point:

```
float noise;             
uint16_t grayValue;      
uint8_t depthConfidence;
```

But in the pointCloud2 field we see `intensity`, `gray`, and `noise`. Any idea what `intensity`, `gray` are? The fields `intensity`, `gray` are the same as `image_mono8` an `image_mono16`, but both follow some sort of auto exposure.

**Comment by kohrt** [comment]
Hi,
`intensity` is the original 16 bit gray value received from the sensor. `gray` is the `intensity` reduced to 8 bit. Auto exposure is done by the sensor an can be disabled.

**Comment by pomerlef** [comment]
Good, thanks for the clarification!
