### ISSUE TITLE
[PicoFlexx::selectCamera] no cameras connected!

### ISSUE THREAD

**Issue by krishnadubba** [code-iai/pico_flexx_driver#8]
Hi,
I am trying this driver on my laptop (Ubuntu 14.04, ROS Indigo, libroyale: 3.1.0.122). I get this error when I try the launch file:

[ERROR] [1491559401.328910949]: [PicoFlexx::selectCamera] no cameras connected!
The camera is connected, but not sure why it is not detected. The following command does give me "camboard_pico_flexx-3-1" in the list. I tried different USB ports and I still get this error.

dksr@ThinkPad$ ls /dev

Cheers,
dksr

**Comment by amaldo** [comment]
Did you add the udev configuration file (according to the libroyale installation instructions)? It sounds like it could be a permissions issue.
